# User Import

class Test ():
	def __init__(self,Cab):
		self.Cab = Cab
		
	def config1_input (self):
		print ('IRFTYP=' , self.Cab.IRFTYP)
		print ('HEIGHT=' , self.Cab.HEIGHT)
		print ('WIDTH=' , self.Cab.WIDTH)
		print ('DEPTH=' , self.Cab.DEPTH)
		print ('WEDGE=' , self.Cab.WEDGE)
		print ('FLANGE=' , self.Cab.FLANGE)
		print ('WEDGER=' , self.Cab.WEDGER)
		print ('FLANGER=' , self.Cab.FLANGER)
		#print ('DOOREDG=' , self.Cab.DOOREDG)
		print ('DGSKT=' , self.Cab.DGSKT)
		print ('CDUP=' , self.Cab.CDUP)
		print ('CDDN=' , self.Cab.CDDN)
		print ('CCHGT=' , self.Cab.CCHGT)
		print ('DOL=' , self.Cab.DOL)
		print ('COL=' , self.Cab.COL)
		print ('DIL=' , self.Cab.DIL)
		print ('CIL=' , self.Cab.CIL)
		print ('TOPMUL=' , self.Cab.TOPMUL)
		print ('THMUL=' , self.Cab.THMUL)
		print ('TIFT=' , self.Cab.TIFT)
		print ('TIFLS=' , self.Cab.TIFLS)
		print ('TIFRS=' , self.Cab.TIFRS)
		print ('TIFF=' , self.Cab.TIFF)
		print ('TIFB=' , self.Cab.TIFB)
		print ('TIRLS=' , self.Cab.TIRLS)
		print ('TIRRS=' , self.Cab.TIRRS)
		print ('TIRF=' , self.Cab.TIRF)
		print ('TIRB=' , self.Cab.TIRB)
		print ('BINSUL=' , self.Cab.BINSUL)
		print ('CINSUL=' , self.Cab.CINSUL)
		print ('HXVUZ=' , self.Cab.HXVUZ)
		print ('VOLAZ=' , self.Cab.VOLAZ)
		print ('HXVUR=' , self.Cab.HXVUR)
		print ('VOLAR=' , self.Cab.VOLAR)
		print ('TROOM=' , self.Cab.TROOM)
		print ('TFRZ=' , self.Cab.TFRZ)
		print ('TFF=' , self.Cab.TFF)
		print ('TBTM=' , self.Cab.TBTM)
		print ('REF alternavite RKINFF=' , self.Cab.RKINFF)
		
		print ('RFRZ= alternative  RKINFZ ' , self.Cab. RKINFZ )
		print ('RWEDGER= alternative WKINR' , self.Cab.WKINR)
		print ('RWEDGE= alternative  WKIN ' , self.Cab. WKIN )
		print ('RDRFF= alternative DKINFF' , self.Cab.DKINFF)
		print ('RDRFZ= alternative DKINFZ' , self.Cab.DKINFZ)
		print ('RMUL= alternative CKMUL' , self.Cab.CKMUL)
		print ('HLFZG=' , self.Cab.HLFZG)
		print ('HLRG=' , self.Cab.HLRG)
		print ('TDRAIR=' , self.Cab.TDRAIR)
		print ('RELHUM=' , self.Cab.RELHUM)
		print ('FFCOPN=' , self.Cab.FFCOPN)
		print ('SECFFC=' , self.Cab.SECFFC)
		print ('FRZOPN=' , self.Cab.FRZOPN)
		print ('SECFRZ=' , self.Cab.SECFRZ)
		print ('FFASHW=' , self.Cab.FFASHW)
		print ('FZASHW=' , self.Cab.FZASHW)
		print ('FFAUXW=' , self.Cab.FFAUXW)
		print ('FZAUXW=' , self.Cab.FZAUXW)
		print ('OTHERW=' , self.Cab.OTHERW)
		print ('FFPENA=' , self.Cab.FFPENA)
		print ('FZPENA=' , self.Cab.FZPENA)
		print ('FFASHQ=' , self.Cab.FFASHQ)
		print ('FZASHQ=' , self.Cab.FZASHQ)
		print ('FFREFQ=' , self.Cab.FFREFQ)
		print ('FZREFQ=' , self.Cab.FZREFQ)
		print ('FFHEAT=' , self.Cab.FFHEAT)
		print ('FZHEAT=' , self.Cab.FZHEAT)

